services:
  - type: web
    name: nextjs-julytype
    region: frankfurt # optional (defaults to oregon)
    rootDir: frontend
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_STRAPI_API_TOKEN
        value: to-be-included
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_STRAPI_API_URL
        value: http://localhost:1337
